### PR TITLE
Create sep_057.md

### PR DESCRIPTION
**Pull request by Gonza10V**
draft SEP057

### CODE REVIEW

**Comment by tcmitchell** [comment]
The SBOL 3.0.1 specification, Section 5.2, states:

> The SBOL namespace MUST NOT be used for any entities or properties not defined in this specification.

This SEP would change that statement to make the SBOL namespace an open set instead of a closed set.

Some options:
* What if we created a child namespace, like `http://sbols.org/v3/bp` or similar, in which these terms can go?
  * Or `http://sbols.org/v3/bp###`?
  * And declare in the specification that this sub-namespace can be used to create new terms
* We could change the spec to make the SBOL3 namespace an open set instead of a closed set, and indicate that "Best Practices" can define new terms.

**Comment by jakebeal** [comment]
I support the child namespace approach, and particularly the first proposal by @tcmitchell of the form `http://sbols.org/v3/bp#TERM`. 

That will keep the set of core SBOL terms a closed set while allowing open addition of BP terms. This will _NOT_ prevent conflict between BP terms, but I view that as a good thing rather than a bad thing, since it will force BPs to take each other into consideration and will avoid confusion between terms that are identical except for BP number.

For the same reason, I also think that we should have a rule that if there is a term `http://sbols.org/v3#TERM` then there MUST NOT be a matching `http://sbols.org/v3/bp#TERM`.

**Comment by cjmyers** [comment]
The difference is that the specification says that only terms defined in the specification can be used.  Validation checks for this.  SEPs result in changes to the specification, so there is no problems.  BPs do not change the specification, so this would break the validation rule check.

**Comment by jakebeal** [comment]
Actually @cjmyers I think there is a problem in the current form, because it says "An SBOL editor will add SBOL terms", but it does not say where the term will be added. It will also result in frequent new specification releases, which the others will not.

**Pull request merged**
