### PR TITLE
SEP17 & SEP18

### PR DESCRIPTION
**Pull request by bbartley**
Hi Editors,

I have drafted two new SEPs and believe they meet the formal requirements.  I just need official editor blessing:

* SEP17 defines ontology terms "design", "build", "test", "learn" and demonstrates how to use them to track provenance with PROV-O annotations
* SEP18 defines the Attachment class, for linking to external data files.

Please merge at your earliest convenience, or let me know if there are any issues!

Regards
Bryan

### CODE REVIEW

**Comment by nroehner** [comment]
Hi Bryan,

Looks good, I have a few comments below. 

I'm close to finishing UML examples for Jake's interlab and CRISPR examples if you'd like to include either in any of the SEPs. I'll share them with you tomorrow.

1. Test should inherit from TopLevel rather than Identified if a "build" object refers to a Test via a white diamond arrow, which I think we want it to be. This allows a user to batch multiple "build" objects derived from the same "design" object by having the former refer to a single Test. 

2. For Figure 1 in SEP 017, I think that the usage labels should be shifted up (and wrapped at the top) by one.

3. For SEP 018, I would maybe make it a little more clear that the reason a Collection is allowed to refer to an Attachment is because Attachment inherits from TopLevel, not because you are adding any new properties to Collection. Maybe the UML example could be tweaked so that both arrows emerge from the same white diamond.

**Comment by nroehner** [comment]
I would also strongly recommend that we reverse direction of the white diamond arrow linking"build" ComponentDefinitions and ModuleDefinitions to Test (or least provide this as an option/competing proposal). This breaks symmetry with the Model class, but I think it makes more sense for updating and versioning objects. 

For example, if you update and make a new version of a Model, then you might want to make new versions of the ModuleDefinitions that referred to the old Model and have these new versions refer to the new Model. 

If you update and make a new version of a Test, however, I see little reason why someone might want to make new versions of the "build" ComponentDefinitions and ModuleDefinitions that previously referred to the old Test. If the arrow were reversed, on the other hand, then I do see why updating and making a new version of a "build" ComponentDefinition or ModuleDefinition might prompt someone to make new versions of any Tests that previously referred to the old "build" objects.

**Comment by cjmyers** [comment]
There is no Test class that I see in the SEP:

https://github.com/bbartley/SEPs/blob/master/sep_017.md

**Comment by cjmyers** [comment]
What UML diagrams are you discussing here?  SEP17 only adds four ontology terms and no new UML.  The UML in Example 1 is simply a demonstration using PROV-O for design-build-test-learn.

**Comment by nroehner** [comment]
For #1, I'm referring to SEP 14 (this pull updates that SEP as well).

**Comment by bbartley** [comment]
Ah.  SEP 14 should be deferred in favor of SEP 17

.

**Comment by nroehner** [comment]
In that case, I would recommend that you clarify in "Relation to Other Proposals" section that, while SEP 17 is compatible with SEP 14, it is meant to be a competing proposal that is adopted instead of SEP 14.

Also, please ignore my original comment on Figure 1 in SEP 17, I was confused about the usage labels. It might help to also label the activity as well so that others could see that it is a build activity using a ModuleDefinition as a design. For some reason the big labels on the left didn't convey this to me originally.

**Comment by nroehner** [comment]
We still need to mark SEP 014 as deprecated.

**Pull request merged**
